# array creation functions

In [6]:
import numpy as np

In [7]:
a= np.array([1,2,3])
print("array a:",a)

array a: [1 2 3]


In [8]:
b= np.arange(0,10,2)
print("array b:",b)

array b: [0 2 4 6 8]


In [9]:
d=np.zeros((2,3))
print(" array d:\n",d)

 array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
d=np.zeros((2,3),dtype=int)
print(" array d:\n",d)

 array d:
 [[0 0 0]
 [0 0 0]]


In [11]:
f=np.eye(4)
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array manipulation functions

In [15]:
a1=np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("reshaped array:",reshaped)

reshaped array: [[1 2 3]]


In [16]:
a1=np.array([1,2,3])
reshaped = np.reshape(a1,(3,1))
print("reshaped array:",reshaped)

reshaped array: [[1]
 [2]
 [3]]


In [17]:
f1=np.array([[1,2],[3,4],[5,6],[7,8]])
flattend=np.ravel(f1)
print("flattend array:",flattend)

flattend array: [1 2 3 4 5 6 7 8]


In [20]:
e1=np.array([[2,4],[5,6]])
transposed=np.transpose(e1)
print("transposed array:\n",transposed)

transposed array:
 [[2 5]
 [4 6]]


In [23]:
a2=np.array([2,4])
b2=np.array([5,6])