In [133]:
import numpy as np

In [134]:
np.__version__

'2.1.3'

In [3]:
my_list =[1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

# Below code we are converting list to array

In [5]:
# pip install numpy

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [13]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [14]:
np.arange(-100,100)

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,
        -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,
        -67,  -66,  -65,  -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,
        -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,  -46,
        -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
        -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,
        -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,
        -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,
         -1,    0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
         10,   11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   

In [20]:
np.arange(-10000,10000)

array([-10000,  -9999,  -9998, ...,   9997,   9998,   9999])

In [21]:
np.arange(10,1) # 1st arg < 2nd arg

array([], dtype=int64)

In [22]:
np.arange(20,10)

array([], dtype=int64)

In [23]:
ar=np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [26]:
ar=(100,129)
ar

(100, 129)

In [27]:
np.arange()

TypeError: arange() requires stop to be specified.

In [28]:
np.arange(10,20,6)

array([10, 16])

In [29]:
np.arange(0,120,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118])

In [32]:
np.arange(10,30,5,3) # it only allow 3 arg \start,stop,step

TypeError: Cannot interpret '3' as a data type

In [36]:
np.zeros(10) # parameter tuuning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros(5,dtype=int) #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [40]:
np.zeros((2,2) ,dtype=int)

array([[0, 0],
       [0, 0]])

In [42]:
zero=np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [43]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [46]:
np.zeros(((10,10)),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [47]:
np.zeros(3)

array([0., 0., 0.])

In [48]:
np.zeros((3) ,dtype=int)

array([0, 0, 0])

In [49]:
np.zeros((10) ,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [53]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [54]:
np.ones((4,8) ,dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [55]:
rand(3,2)

NameError: name 'rand' is not defined

In [56]:
random(2,3)

NameError: name 'random' is not defined

In [61]:
np.random.rand(3)

array([0.96470947, 0.42357681, 0.93867003])

In [60]:
np.rand(5)

AttributeError: module 'numpy' has no attribute 'rand'

In [63]:
np.random.rand(20)

array([0.73231484, 0.37947983, 0.81378299, 0.05434233, 0.54509781,
       0.11367644, 0.77831914, 0.18174122, 0.8742867 , 0.49562845,
       0.08681352, 0.41478474, 0.86207155, 0.48042097, 0.93633745,
       0.85676604, 0.78655833, 0.83567915, 0.20226269, 0.24135662])

In [64]:
np.random.rand(3,1)

array([[0.07363525],
       [0.82081998],
       [0.94209695]])

In [65]:
np.random.rand(3,3)

array([[0.31821751, 0.79326225, 0.15456729],
       [0.67041391, 0.78698013, 0.90985654],
       [0.75171334, 0.10538537, 0.6657119 ]])

In [68]:
np.random.rand(6,4)

array([[0.22701328, 0.88381438, 0.42627885, 0.65724379],
       [0.03242407, 0.20438244, 0.24490841, 0.60266441],
       [0.05343744, 0.48824329, 0.33816104, 0.81332602],
       [0.23843824, 0.32625627, 0.09013326, 0.76344637],
       [0.8739157 , 0.91450477, 0.91561095, 0.59319827],
       [0.07498543, 0.85860621, 0.0776662 , 0.47832352]])

In [91]:
np.random.randint(3,8)

3

In [97]:
np.random.randint(3,9,6)

array([5, 5, 7, 3, 6, 8], dtype=int32)

In [98]:
np.random.rand(0,1)

array([], shape=(0, 1), dtype=float64)

In [101]:
np.random.randint(0,1)

0

In [102]:
np.random.randint(30,20,10)

ValueError: low >= high

In [103]:
np.random.randint(-30,20,10)

array([-23,  16,  -5,  17, -19, -22,   2,  -5,  14,   8], dtype=int32)

In [104]:
np.random.randint(-30,20,10,2)

TypeError: Cannot interpret '2' as a data type

In [106]:
np.random.randint(10,40,(10,10))

array([[31, 32, 23, 24, 34, 39, 15, 18, 33, 36],
       [17, 12, 25, 37, 17, 34, 39, 34, 39, 29],
       [34, 12, 19, 28, 23, 26, 32, 21, 32, 20],
       [12, 23, 33, 21, 22, 38, 24, 31, 17, 25],
       [24, 19, 18, 34, 29, 24, 16, 36, 17, 13],
       [17, 37, 30, 28, 36, 35, 23, 11, 27, 39],
       [10, 20, 38, 35, 10, 25, 23, 31, 26, 16],
       [36, 22, 25, 29, 21, 23, 20, 15, 19, 21],
       [13, 27, 29, 13, 11, 15, 29, 17, 24, 39],
       [14, 15, 21, 35, 35, 23, 32, 15, 10, 14]], dtype=int32)

In [107]:
np.random.randint(10,400,(10,15))

array([[131, 118, 197,  84, 311, 152, 325, 289, 118, 134, 118,  34, 294,
        139, 379],
       [ 13, 232,  91,  39, 112,  70, 328, 266, 113,  38, 267, 171, 286,
        242, 159],
       [389,  50, 145, 147, 116, 361, 183, 144, 208, 114,  76, 225,  20,
        390, 126],
       [243, 236, 100, 235, 186, 106,  75,  39, 121, 180, 229, 143,  14,
        374, 168],
       [182, 344, 254, 241, 253, 386, 329, 274,  15, 301, 245, 262, 386,
        347, 180],
       [ 95, 287,  27,  33, 374, 209, 267, 301, 159,  13, 201, 373, 308,
         21, 134],
       [160, 206, 244,  77,  53, 109, 341,  41, 211, 208, 356, 124, 281,
        266,  68],
       [145, 172, 374, 207, 148, 200, 226,  69, 181, 122, 136, 221, 283,
        175, 328],
       [353, 396, 236,  76, 144, 324,  85, 230, 285,  29, 270, 271, 316,
         50, 265],
       [ 24, 241, 133, 125, 162,  96, 152, 152, 266,  23, 171, 233, 194,
        108, 191]], dtype=int32)

In [108]:
arr

array([1, 2, 3, 4, 5])

In [110]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [112]:
np.arange(1,13).reshape(4,4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [113]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [115]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [116]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [117]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

#  Slicing in Matrix

In [137]:
b= np.random.randint(10,20,(5,4))
b

array([[18, 17, 11, 12],
       [10, 18, 19, 18],
       [13, 17, 13, 19],
       [13, 11, 14, 17],
       [13, 14, 14, 19]], dtype=int32)

In [138]:
b[:]

array([[18, 17, 11, 12],
       [10, 18, 19, 18],
       [13, 17, 13, 19],
       [13, 11, 14, 17],
       [13, 14, 14, 19]], dtype=int32)

In [139]:
b[0]

array([18, 17, 11, 12], dtype=int32)

In [140]:
b[3]

array([13, 11, 14, 17], dtype=int32)

In [141]:
type(b)

numpy.ndarray

In [142]:
b

array([[18, 17, 11, 12],
       [10, 18, 19, 18],
       [13, 17, 13, 19],
       [13, 11, 14, 17],
       [13, 14, 14, 19]], dtype=int32)

In [143]:
b[:]

array([[18, 17, 11, 12],
       [10, 18, 19, 18],
       [13, 17, 13, 19],
       [13, 11, 14, 17],
       [13, 14, 14, 19]], dtype=int32)

In [144]:
b[1:3]

array([[10, 18, 19, 18],
       [13, 17, 13, 19]], dtype=int32)

In [145]:
b

array([[18, 17, 11, 12],
       [10, 18, 19, 18],
       [13, 17, 13, 19],
       [13, 11, 14, 17],
       [13, 14, 14, 19]], dtype=int32)

In [147]:
b[1,2]

np.int32(19)

In [148]:
b[1,3]

np.int32(18)

In [149]:
b[1,1]

np.int32(18)

In [150]:
b[2,0]

np.int32(13)

In [151]:
b[0,1]

np.int32(17)

In [152]:
b

array([[18, 17, 11, 12],
       [10, 18, 19, 18],
       [13, 17, 13, 19],
       [13, 11, 14, 17],
       [13, 14, 14, 19]], dtype=int32)

In [153]:
b[0,0]

np.int32(18)

In [154]:
b[0,-3]

np.int32(17)

In [156]:
b[0:-3]

array([[18, 17, 11, 12],
       [10, 18, 19, 18]], dtype=int32)

In [157]:
b[-4,3]

np.int32(18)

In [158]:
b

array([[18, 17, 11, 12],
       [10, 18, 19, 18],
       [13, 17, 13, 19],
       [13, 11, 14, 17],
       [13, 14, 14, 19]], dtype=int32)

In [159]:
b[-1,1]

np.int32(14)

In [166]:
b[-5,3]

np.int32(12)

In [167]:
np.random.randint(10,20,(4,4))

array([[13, 14, 17, 13],
       [16, 18, 19, 19],
       [17, 10, 14, 13],
       [18, 13, 10, 13]], dtype=int32)

In [170]:
a=np.random.randint(10,20,10)
a

array([10, 11, 12, 13, 13, 13, 14, 16, 11, 16], dtype=int32)

In [171]:
id(a)

2859782060912

In [173]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[12, 90, 86, 51, 87, 41, 94, 71, 88, 60],
       [84, 42, 37, 14, 80, 15, 30,  5, 47, 91],
       [12, 77, 29,  0, 93, 15, 56, 71, 41, 89],
       [27, 85,  0, 29, 84, 30, 11, 79, 27, 84],
       [33,  6, 11, 96, 17, 26, 32, 80,  4, 56],
       [ 9, 34, 44, 52, 74, 67, 14, 21, 12, 87],
       [58, 28, 26, 27, 27, 85,  0, 78, 27, 95],
       [65, 60, 57, 24, 36, 40, 19, 70, 39, 43],
       [81, 57, 92, 67, 24, 76, 64, 56, 46, 26],
       [16, 93, 18, 23, 49, 61, 77, 68, 93, 16]], dtype=int32)

In [175]:
arr

array([1, 2, 3, 4, 5])

In [176]:
arr

array([1, 2, 3, 4, 5])

In [177]:
arr[:3]

array([1, 2, 3])

In [180]:
arr[:]

array([1, 2, 3, 4, 5])

In [181]:
arr2[:]

array([[12, 90, 86, 51, 87, 41, 94, 71, 88, 60],
       [84, 42, 37, 14, 80, 15, 30,  5, 47, 91],
       [12, 77, 29,  0, 93, 15, 56, 71, 41, 89],
       [27, 85,  0, 29, 84, 30, 11, 79, 27, 84],
       [33,  6, 11, 96, 17, 26, 32, 80,  4, 56],
       [ 9, 34, 44, 52, 74, 67, 14, 21, 12, 87],
       [58, 28, 26, 27, 27, 85,  0, 78, 27, 95],
       [65, 60, 57, 24, 36, 40, 19, 70, 39, 43],
       [81, 57, 92, 67, 24, 76, 64, 56, 46, 26],
       [16, 93, 18, 23, 49, 61, 77, 68, 93, 16]], dtype=int32)

In [182]:
arr2[0:5]

array([[12, 90, 86, 51, 87, 41, 94, 71, 88, 60],
       [84, 42, 37, 14, 80, 15, 30,  5, 47, 91],
       [12, 77, 29,  0, 93, 15, 56, 71, 41, 89],
       [27, 85,  0, 29, 84, 30, 11, 79, 27, 84],
       [33,  6, 11, 96, 17, 26, 32, 80,  4, 56]], dtype=int32)

In [183]:
arr[1:4]

array([2, 3, 4])

In [184]:
arr2[-2,2]

np.int32(92)

In [186]:
arr2[-2,-2]

np.int32(46)

In [187]:
arr2[::-1]

array([[16, 93, 18, 23, 49, 61, 77, 68, 93, 16],
       [81, 57, 92, 67, 24, 76, 64, 56, 46, 26],
       [65, 60, 57, 24, 36, 40, 19, 70, 39, 43],
       [58, 28, 26, 27, 27, 85,  0, 78, 27, 95],
       [ 9, 34, 44, 52, 74, 67, 14, 21, 12, 87],
       [33,  6, 11, 96, 17, 26, 32, 80,  4, 56],
       [27, 85,  0, 29, 84, 30, 11, 79, 27, 84],
       [12, 77, 29,  0, 93, 15, 56, 71, 41, 89],
       [84, 42, 37, 14, 80, 15, 30,  5, 47, 91],
       [12, 90, 86, 51, 87, 41, 94, 71, 88, 60]], dtype=int32)

In [193]:
arr2

array([[12, 90, 86, 51, 87, 41, 94, 71, 88, 60],
       [84, 42, 37, 14, 80, 15, 30,  5, 47, 91],
       [12, 77, 29,  0, 93, 15, 56, 71, 41, 89],
       [27, 85,  0, 29, 84, 30, 11, 79, 27, 84],
       [33,  6, 11, 96, 17, 26, 32, 80,  4, 56],
       [ 9, 34, 44, 52, 74, 67, 14, 21, 12, 87],
       [58, 28, 26, 27, 27, 85,  0, 78, 27, 95],
       [65, 60, 57, 24, 36, 40, 19, 70, 39, 43],
       [81, 57, 92, 67, 24, 76, 64, 56, 46, 26],
       [16, 93, 18, 23, 49, 61, 77, 68, 93, 16]], dtype=int32)

In [190]:
arr2[::-2]

array([[16, 93, 18, 23, 49, 61, 77, 68, 93, 16],
       [65, 60, 57, 24, 36, 40, 19, 70, 39, 43],
       [ 9, 34, 44, 52, 74, 67, 14, 21, 12, 87],
       [27, 85,  0, 29, 84, 30, 11, 79, 27, 84],
       [84, 42, 37, 14, 80, 15, 30,  5, 47, 91]], dtype=int32)

In [192]:
arr2[::-4]

array([[16, 93, 18, 23, 49, 61, 77, 68, 93, 16],
       [ 9, 34, 44, 52, 74, 67, 14, 21, 12, 87],
       [84, 42, 37, 14, 80, 15, 30,  5, 47, 91]], dtype=int32)

In [194]:
arr

array([1, 2, 3, 4, 5])

In [196]:
arr.max()

np.int64(5)

In [197]:
arr.min()

np.int64(1)

In [198]:
arr.mean()

np.float64(3.0)

In [199]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [207]:
from numpy import *
a = array([1,2,6,4,5,9])
median(a)

np.float64(4.5)

# working work on import * can you please find the median,mode

In [215]:
arr=(2,3,4,5,6,7)
arr

(2, 3, 4, 5, 6, 7)

In [216]:
arr.reshape(3,2)

AttributeError: 'tuple' object has no attribute 'reshape'

In [217]:
my_list =[1,2,3,4,5,6]
my_list

[1, 2, 3, 4, 5, 6]

In [218]:
arr = np.array(my_list)

In [219]:
arr

array([1, 2, 3, 4, 5, 6])

In [220]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [221]:
arr.reshape(2,3,order='C') 

array([[1, 2, 3],
       [4, 5, 6]])

In [223]:
arr.reshape(2,3,order='F') 

array([[1, 3, 5],
       [2, 4, 6]])

In [224]:
arr.reshape(2,3,order='A') 

array([[1, 2, 3],
       [4, 5, 6]])

In [225]:
arr.reshape(2,3) 

array([[1, 2, 3],
       [4, 5, 6]])

In [227]:
arr.reshape(1,3) 

ValueError: cannot reshape array of size 6 into shape (1,3)

# Indexing

In [228]:
mat=np.arange(0,100).reshape(10,10)

In [229]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [230]:
row=4
col=5

In [231]:
row

4

In [232]:
col

5

In [233]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [234]:
mat[row,col]

np.int64(45)

In [235]:
mat[4,5]

np.int64(45)

In [237]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [238]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [239]:
col =6

In [240]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [241]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [242]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [243]:
mat[:,row]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [245]:
mat[row:,]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [246]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [249]:
mat[3:3]

array([], shape=(0, 10), dtype=int64)

In [250]:
mat[-3:3]

array([], shape=(0, 10), dtype=int64)

In [253]:
mat[5:9]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [252]:
mat[0:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [254]:
mat[0:10:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [255]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [256]:
mat[::1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [258]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

# Masking

In [259]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [260]:
id(mat)

2859782881168

In [261]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [265]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [266]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [263]:
mat[mat==50]

array([50])

In [ ]:
mat

In [267]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])